@push('styles')
    .crm-hero-copy{max-width:690px}.crm-lead+.crm-lead{margin-top:11px}.crm-hero-art{min-height:430px}.crm-dashboard{position:absolute;inset:25px;z-index:2;padding:24px;color:#fff;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.11);border-radius:22px}.crm-dashboard-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:22px}.crm-dashboard-head b{font-size:15px}.crm-dashboard-head span{padding:4px 9px;color:var(--cyan);background:rgba(18,214,210,.1);border:1px solid rgba(18,214,210,.2);border-radius:99px;font-size:10px}.crm-customer{display:flex;align-items:center;gap:11px;margin-bottom:12px;padding:13px;background:rgba(255,255,255,.06);border-radius:14px}.crm-avatar{display:grid;width:38px;height:38px;place-items:center;color:var(--navy);background:#fff;border-radius:12px;font-weight:900}.crm-customer div{flex:1}.crm-customer b,.crm-customer small{display:block}.crm-customer b{font-size:12px}.crm-customer small{color:rgba(255,255,255,.55);font-size:10px}.crm-state{color:var(--cyan);font-size:10px}.crm-pipeline{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:18px}.crm-pipeline div{padding:12px 8px;text-align:center;background:rgba(255,255,255,.055);border-radius:12px}.crm-pipeline b,.crm-pipeline span{display:block}.crm-pipeline b{color:var(--cyan);font-size:16px}.crm-pipeline span{color:rgba(255,255,255,.55);font-size:9px}
    .crm-intro{max-width:900px;margin:-25px auto 40px;color:var(--muted);font-size:15px;line-height:2.2;text-align:center}.crm-problem{padding:30px;color:#fff;background:linear-gradient(135deg,var(--navy),var(--navy-900));border-radius:23px}.crm-problem strong{display:block;margin-bottom:10px;color:var(--cyan);font-size:14px}.crm-problem p{margin:0;color:rgba(255,255,255,.74);font-size:14px;line-height:2.15}.crm-problem-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:20px}.crm-problem-card{padding:27px;background:#fff;border:1px solid var(--line);border-radius:21px}.crm-problem-card h3{margin:0 0 10px;color:var(--navy);font-size:17px}.crm-problem-card p{margin:0;color:var(--muted);font-size:14px;line-height:2.1}.crm-outcomes{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin:28px 0 0;padding:0;list-style:none}.crm-outcomes li{padding:18px;color:#385269;background:#eaf5f5;border-radius:15px;font-weight:700;text-align:center}
    .crm-capability-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.crm-capability{position:relative;padding:28px 72px 28px 27px;background:#fff;border:1px solid var(--line);border-radius:21px;transition:.25s}.crm-capability:hover{border-color:var(--teal);transform:translateY(-4px);box-shadow:var(--shadow)}.crm-capability-num{position:absolute;top:27px;right:24px;display:grid;width:34px;height:34px;place-items:center;color:var(--teal-dark);background:#e7f4f4;border-radius:11px;font-size:11px;font-weight:900}.crm-capability h3{margin:0 0 9px;color:var(--navy);font-size:17px}.crm-capability p{margin:0;color:var(--muted);font-size:14px;line-height:2.05}
    .crm-process-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.crm-process{position:relative;padding:29px;background:#fff;border:1px solid var(--line);border-radius:21px}.crm-process-step{display:grid;width:43px;height:43px;margin-bottom:18px;place-items:center;color:#fff;background:var(--teal);border-radius:13px;font-weight:900}.crm-process h3{margin:0 0 10px;color:var(--navy);font-size:18px}.crm-process p{margin:0 0 17px;color:var(--muted);font-size:14px;line-height:2.1}.crm-process a{display:inline-flex;color:var(--teal-dark);font-size:12px;font-weight:700}.crm-process a:hover{color:var(--navy)}
    .crm-benefit-intro{max-width:850px;margin:16px auto 40px;color:rgba(255,255,255,.68);font-size:15px;line-height:2.2;text-align:center}.crm-benefits-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:13px;margin:0;padding:0;list-style:none}.crm-benefits-grid li{position:relative;padding:19px 48px 19px 18px;color:rgba(255,255,255,.82);background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.09);border-radius:15px;font-weight:600}.crm-benefits-grid li:before{content:"✓";position:absolute;right:17px;top:18px;display:grid;width:22px;height:22px;place-items:center;color:var(--navy);background:var(--cyan);border-radius:7px;font-size:11px;font-weight:900}
    .crm-audience-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.crm-audience{padding:23px;background:#fff;border:1px solid var(--line);border-radius:18px}.crm-audience h3{margin:0 0 7px;color:var(--navy);font-size:15px}.crm-audience p{margin:0;color:var(--muted);font-size:13px;line-height:2}.crm-faq-intro{max-width:760px;margin:-22px auto 36px;color:var(--muted);font-size:14px;line-height:2.1;text-align:center}
    @media(max-width:1050px){.crm-audience-grid{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:840px){.crm-hero-art{min-height:410px}.crm-problem-grid,.crm-outcomes,.crm-capability-grid,.crm-process-grid,.crm-benefits-grid{grid-template-columns:1fr}.crm-intro{margin-top:-10px}.crm-benefits-grid{max-width:650px;margin-inline:auto}}
    @media(max-width:580px){.crm-dashboard{inset:18px;padding:17px}.crm-pipeline{grid-template-columns:1fr}.crm-customer{padding:10px}.crm-problem{padding:24px}.crm-audience-grid{grid-template-columns:1fr}.crm-capability{padding:72px 23px 24px}.crm-capability-num{top:22px;right:22px}.crm-intro,.crm-benefit-intro{font-size:13px}}
@endpush
