<?php
    $title = 'درباره سپند | فناوری برای یک مسیر شفاف‌تر';
    $description = 'درباره سپند، نگاه ما به مدیریت هوشمند حمل‌ونقل و ارزش‌هایی که مسیر همکاری را شکل می‌دهند.';
?>

<?php $__env->startSection('content'); ?>
<section class="page-hero">
    <div class="container hero-inner">
        <div class="hero-copy reveal"><div class="breadcrumb"><a href="<?php echo e(route('home')); ?>">صفحه اصلی</a><svg viewBox="0 0 24 24" fill="none"><path d="m9 18 6-6-6-6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg><span>درباره ما</span></div><h1>فناوری وقتی ارزشمند است<br>که مسیر را <span>روشن‌تر کند</span></h1><p>سپند با همین باور شکل گرفته است: ابزارهای پیچیده باید به تجربه‌ای ساده تبدیل شوند؛ تجربه‌ای که تیم‌ها را هماهنگ، تصمیم‌ها را دقیق و ارتباط با مشتری را قابل‌اعتمادتر کند.</p><div class="hero-actions"><a class="btn btn-primary" href="#story">داستان سپند</a><a class="btn btn-outline" href="<?php echo e(route('modules')); ?>">راهکارهای ما</a></div></div>
        <div class="hero-art reveal"><div class="art-panel"><div class="art-content"><div class="art-head"><span class="art-mark"><img src="<?php echo e(asset('assets/images/brand/sepand-provided-header.png')); ?>" alt="" style="width:38px;height:38px;object-fit:contain"></span><span class="art-chip">نگاه سپند</span></div><h2 class="art-title">فراتر از یک نرم‌افزار</h2><p class="art-desc">یک زبان مشترک برای مشتری، عملیات و مدیریت</p><div class="art-bars"><i></i><i></i><i></i><i></i><i></i><i></i></div></div></div></div>
    </div>
</section>

<section class="section" id="story">
    <div class="container split">
        <div class="visual-box reveal"><span class="section-label">ماموریت ما</span><h2 style="margin:14px 0 22px;font-size:30px;line-height:1.75">تبدیل پیچیدگی عملیات<br>به جریان کاری روشن</h2><p style="margin:0;color:rgba(255,255,255,.63);line-height:2.2">می‌خواهیم هر عضو تیم بداند چه کاری، در چه زمانی و بر پایه چه اطلاعاتی باید انجام شود؛ بدون ابهام، بدون داده‌های پراکنده و بدون دوباره‌کاری.</p></div>
        <div class="split-copy reveal"><span class="section-label">داستان سپند</span><h2 class="section-title">از دل یک نیاز واقعی؛<br><span>برای حل یک مسئله واقعی</span></h2><p>کسب‌وکارهای حمل‌ونقل با حجم زیادی از ارتباطات، اسناد، وظایف و تصمیم‌های به‌هم‌پیوسته روبه‌رو هستند. سپند برای پیوند دادن همین اجزا شکل گرفت؛ پلتفرمی که به‌جای افزودن پیچیدگی، نظم و شفافیت ایجاد کند.</p><p>ما نرم‌افزار را پایان کار نمی‌دانیم. شناخت فرایند، همراهی در استقرار و یادگیری از تجربه کاربران بخشی از محصولی است که هر روز بهتر می‌شود.</p><div class="check-grid"><span class="check"><i>✓</i>شناخت عمیق فرایند</span><span class="check"><i>✓</i>طراحی انسان‌محور</span><span class="check"><i>✓</i>توسعه مستمر</span><span class="check"><i>✓</i>همراهی بلندمدت</span></div></div>
    </div>
</section>

<section class="dark-section">
    <div class="container"><div class="section-head reveal"><span class="section-label">ارزش‌های ما</span><h2 class="section-title">اصولی که هر تصمیم را<br><span>هدایت می‌کنند</span></h2></div><div class="values"><article class="value reveal"><svg viewBox="0 0 24 24" fill="none"><path d="M3 12s3-6 9-6 9 6 9 6-3 6-9 6-9-6-9-6Z" stroke="currentColor" stroke-width="1.7"/><circle cx="12" cy="12" r="2.5" stroke="currentColor" stroke-width="1.7"/></svg><b>شفافیت</b><p>اطلاعات روشن، مسئولیت مشخص و گفت‌وگوی صادقانه پایه اعتماد است.</p></article><article class="value reveal"><svg viewBox="0 0 24 24" fill="none"><path d="M12 21s7-3 7-9V5l-7-2-7 2v7c0 6 7 9 7 9Z" stroke="currentColor" stroke-width="1.7"/><path d="m9 12 2 2 4-5" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg><b>اعتمادپذیری</b><p>محصول و تیم ما باید در لحظه‌های حساس، قابل اتکا و پاسخ‌گو باشند.</p></article><article class="value reveal"><svg viewBox="0 0 24 24" fill="none"><path d="M4 15c4-8 8-8 16-8-1 8-5 12-12 11M4 20c2-5 6-8 11-10" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg><b>رشد مستمر</b><p>هر بازخورد فرصتی برای ساختن تجربه‌ای ساده‌تر و اثربخش‌تر است.</p></article><article class="value reveal"><svg viewBox="0 0 24 24" fill="none"><path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm8 0a4 4 0 1 0 0-8M2 21a6 6 0 0 1 12 0m2-6a6 6 0 0 1 6 6" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg><b>همراهی</b><p>موفقیت مشتری را یک پروژه مشترک و یک رابطه بلندمدت می‌بینیم.</p></article></div></div>
</section>

<section class="section soft"><div class="container"><div class="section-head reveal"><span class="section-label">روش کار ما</span><h2 class="section-title">از شنیدن تا ساختن؛<br><span>کنار تیم شما</span></h2><p class="section-sub">راهکار خوب با شناخت دقیق شروع می‌شود و با اندازه‌گیری نتیجه ادامه پیدا می‌کند.</p></div><div class="card-grid"><article class="content-card reveal"><span class="card-icon"><svg viewBox="0 0 24 24" fill="none"><path d="M4 13a8 8 0 0 1 16 0v5a2 2 0 0 1-2 2h-2v-7h4M4 13v7H2a2 2 0 0 1-2-2v-5h4Z" stroke="currentColor" stroke-width="1.7"/></svg></span><h3>اول گوش می‌دهیم</h3><p>مسئله، محدودیت‌ها و اولویت‌های واقعی تیم شما را بدون پیش‌فرض بررسی می‌کنیم.</p></article><article class="content-card reveal"><span class="card-icon"><svg viewBox="0 0 24 24" fill="none"><path d="M4 6h5v5H4V6Zm11 7h5v5h-5v-5ZM9 8h3a4 4 0 0 1 4 4v1M15 16h-3a4 4 0 0 1-4-4v-1" stroke="currentColor" stroke-width="1.7"/></svg></span><h3>سپس طراحی می‌کنیم</h3><p>فرایند و ترکیب ماژول‌ها را متناسب با ساختار سازمان شما شکل می‌دهیم.</p></article><article class="content-card reveal"><span class="card-icon"><svg viewBox="0 0 24 24" fill="none"><path d="M4 19V9m5 10V5m5 14v-7m5 7V3" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg></span><h3>نتیجه را می‌سنجیم</h3><p>پس از استقرار، بازخورد و شاخص‌ها مسیر بهبود مستمر را مشخص می‌کنند.</p></article></div></div></section>

<section class="cta-wrap"><div class="container"><div class="cta reveal"><div class="cta-copy"><h2>بیایید مسیر بعدی را با هم بسازیم</h2><p>اگر به دنبال یک شریک فناوری برای منظم‌کردن فرایندهای خود هستید، آماده گفت‌وگو هستیم.</p></div><div class="cta-action"><a class="btn" href="<?php echo e(route('home')); ?>#contact">شروع گفت‌وگو</a></div></div></div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.marketing', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /var/www/sepand-crm/portal-customer-site/resources/views/marketing/about.blade.php ENDPATH**/ ?>