<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    @php
        $pageTitle = $title ?? 'نرم‌افزار CRM و مدیریت عملیات حمل‌ونقل | سپند';
        $pageDescription = $description ?? 'سپند؛ نرم‌افزار یکپارچه CRM، فروش، عملیات، اسناد و مالی برای شرکت‌های حمل‌ونقل، فورواردری و لجستیک.';
        $canonicalUrl = $canonical ?? url()->current();
    @endphp
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#0f305b">
    <meta name="robots" content="index,follow,max-image-preview:large">
    <meta name="description" content="{{ $pageDescription }}">
    <meta property="og:locale" content="fa_IR">
    <meta property="og:type" content="website">
    <meta property="og:title" content="{{ $pageTitle }}">
    <meta property="og:description" content="{{ $pageDescription }}">
    <meta property="og:url" content="{{ $canonicalUrl }}">
    <meta property="og:site_name" content="سپند">
    <meta property="og:image" content="{{ asset('assets/images/marketing/sepand-cargo-details.webp') }}">
    <link rel="canonical" href="{{ $canonicalUrl }}">
    <title>{{ $pageTitle }}</title>
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('assets/images/favicon.png') }}?v=20260801">
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('favicon.ico') }}?v=20260801">
    @if(config('services.ga4.measurement_id'))
        <script async src="https://www.googletagmanager.com/gtag/js?id={{ rawurlencode(config('services.ga4.measurement_id')) }}"></script>
        <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config',@json(config('services.ga4.measurement_id')));</script>
    @endif
    @stack('head')
    <script>document.documentElement.classList.add('js');</script>
    <style>
        @font-face{font-family:IRANSans;src:url("{{ asset('fonts/iransans/woff2/IRANSansWeb(FaNum).woff2') }}") format("woff2");font-weight:400;font-display:swap}
        @font-face{font-family:IRANSans;src:url("{{ asset('fonts/iransans/woff2/IRANSansWeb(FaNum)_Medium.woff2') }}") format("woff2");font-weight:500;font-display:swap}
        @font-face{font-family:IRANSans;src:url("{{ asset('fonts/iransans/woff2/IRANSansWeb(FaNum)_Bold.woff2') }}") format("woff2");font-weight:700;font-display:swap}
        @font-face{font-family:IRANSans;src:url("{{ asset('fonts/iransans/woff2/IRANSansWeb(FaNum)_Black.woff2') }}") format("woff2");font-weight:900;font-display:swap}
        :root{--navy:#0f305b;--navy-900:#081e39;--teal:#2f9196;--teal-dark:#24777c;--cyan:#12d6d2;--ink:#11243a;--muted:#65758a;--cloud:#f3f8f8;--line:#dce9e9;--white:#fff;--shadow:0 24px 65px rgba(15,48,91,.11)}
        *,*:before,*:after{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:92px;max-width:100%;overflow-x:clip}body{margin:0;max-width:100%;overflow-x:clip;color:var(--ink);background:#fff;font-family:IRANSans,Tahoma,sans-serif;font-size:14px;line-height:1.9;-webkit-font-smoothing:antialiased}body.menu-open{overflow:hidden}a{color:inherit;text-decoration:none}button{font:inherit;cursor:pointer}img,svg{display:block}p{text-align:justify!important;text-align-last:right!important;text-justify:inter-word}.container{width:min(1180px,calc(100% - 40px));margin-inline:auto}.skip{position:fixed;top:-70px;right:18px;z-index:300;padding:9px 17px;color:#fff;background:var(--navy);border-radius:10px}.skip:focus{top:12px}
        .site-header{position:fixed;inset:0 0 auto;z-index:100;height:82px;display:flex;align-items:center;border-bottom:1px solid rgba(15,48,91,.07);background:rgba(255,255,255,.91);box-shadow:0 8px 34px rgba(15,48,91,.055);backdrop-filter:blur(16px)}.nav-wrap{display:flex;align-items:center;justify-content:space-between;gap:28px}.brand{display:inline-flex;width:66px;height:50px;align-items:center;justify-content:center;flex:0 0 66px}.brand img{width:64px;height:48px;object-fit:contain}.main-nav{display:flex;align-items:center;gap:28px;margin-right:auto}.main-nav>a{position:relative;color:#415369;font-size:13px;font-weight:500}.main-nav>a:after{content:"";position:absolute;right:0;left:100%;bottom:-9px;height:2px;background:var(--teal);border-radius:2px;transition:.25s}.main-nav>a:hover,.main-nav>a.active{color:var(--navy)}.main-nav>a:hover:after,.main-nav>a.active:after{left:0}.portal-actions{display:flex;align-items:center;gap:7px}.portal-link{display:inline-flex;position:relative;min-height:42px;padding:0 12px;align-items:center;justify-content:center;gap:7px;color:var(--navy);background:#fff;border:1px solid rgba(15,48,91,.14);border-radius:12px;font-size:10px;font-weight:700;white-space:nowrap;transition:.22s}.portal-link:hover{color:var(--teal-dark);border-color:var(--teal);transform:translateY(-2px)}.portal-link svg{width:16px}.portal-link.primary{color:#fff;background:var(--navy);border-color:var(--navy);box-shadow:0 9px 22px rgba(15,48,91,.16)}.portal-link.primary:hover{color:#fff;background:var(--teal-dark);border-color:var(--teal-dark)}.new-badge{position:absolute;top:-9px;right:9px;padding:1px 7px;color:#fff;background:#20b889;border:2px solid #fff;border-radius:20px;font-size:8px;line-height:1.6}.mobile-portals{display:none}.menu-toggle{display:none;width:44px;height:44px;padding:0;place-items:center;color:var(--navy);background:#fff;border:1px solid var(--line);border-radius:12px}.menu-toggle svg{width:22px}
        .page-hero{position:relative;padding:165px 0 95px;overflow:hidden;background:radial-gradient(circle at 12% 15%,rgba(18,214,210,.1),transparent 27%),linear-gradient(180deg,#f7fbfc,#fff)}.page-hero:before{content:"";position:absolute;inset:0;opacity:.35;background-image:radial-gradient(rgba(15,48,91,.18) .7px,transparent .7px);background-size:26px 26px;mask-image:linear-gradient(#000,transparent 92%)}.page-hero:after{content:"";position:absolute;width:370px;height:370px;left:-200px;top:80px;border:1px solid rgba(47,145,150,.16);border-radius:50%;box-shadow:0 0 0 65px rgba(47,145,150,.025),0 0 0 130px rgba(47,145,150,.015)}.hero-inner{position:relative;z-index:2;display:grid;grid-template-columns:1.08fr .92fr;align-items:center;gap:75px}.breadcrumb{display:flex;align-items:center;gap:8px;margin-bottom:20px;color:var(--teal-dark);font-size:11px;font-weight:600}.breadcrumb a{color:#7b8a9c}.breadcrumb svg{width:13px}.page-hero h1{margin:0 0 18px;color:var(--navy-900);font-size:clamp(38px,5vw,62px);line-height:1.45;letter-spacing:-2px;font-weight:900}.page-hero h1 span{color:var(--teal)}.page-hero p{max-width:640px;margin:0;color:var(--muted);font-size:16px;line-height:2.15}.hero-actions{display:flex;gap:11px;margin-top:29px}.btn{display:inline-flex;min-height:52px;padding:0 23px;align-items:center;justify-content:center;gap:9px;border:1px solid transparent;border-radius:14px;font-weight:700;transition:.25s}.btn svg{width:18px}.btn-primary{color:#fff;background:var(--navy);box-shadow:0 14px 29px rgba(15,48,91,.2)}.btn-primary:hover{background:var(--teal-dark);transform:translateY(-3px)}.btn-outline{color:var(--navy);background:#fff;border-color:rgba(15,48,91,.14)}.btn-outline:hover{color:var(--teal-dark);border-color:var(--teal);transform:translateY(-3px)}
        .hero-art{position:relative;min-height:350px}.art-panel{position:absolute;inset:0;padding:25px;color:#fff;background:var(--navy);border-radius:30px;box-shadow:0 30px 70px rgba(15,48,91,.21);overflow:hidden}.art-panel:before{content:"";position:absolute;width:330px;height:330px;left:-130px;top:-160px;border:1px solid rgba(18,214,210,.24);border-radius:50%;box-shadow:0 0 0 55px rgba(18,214,210,.025),0 0 0 110px rgba(18,214,210,.018)}.art-panel:after{content:"";position:absolute;inset:0;opacity:.13;background-image:radial-gradient(#fff .7px,transparent .7px);background-size:23px 23px}.art-content{position:relative;z-index:2}.art-head{display:flex;align-items:center;justify-content:space-between}.art-mark{display:grid;width:52px;height:52px;place-items:center;color:var(--navy);background:#fff;border-radius:16px}.art-mark svg{width:27px}.art-chip{padding:5px 10px;color:var(--cyan);background:rgba(18,214,210,.1);border:1px solid rgba(18,214,210,.2);border-radius:99px;font-size:9px;font-weight:700}.art-title{margin:36px 0 6px;font-size:22px;font-weight:800}.art-desc{color:rgba(255,255,255,.6);font-size:11px}.art-bars{display:flex;align-items:end;gap:10px;height:90px;margin-top:26px;padding:15px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.09);border-radius:18px;direction:ltr}.art-bars i{display:block;flex:1;background:linear-gradient(180deg,var(--cyan),rgba(18,214,210,.17));border-radius:6px 6px 2px 2px}.art-bars i:nth-child(1){height:34%}.art-bars i:nth-child(2){height:62%}.art-bars i:nth-child(3){height:45%}.art-bars i:nth-child(4){height:83%}.art-bars i:nth-child(5){height:69%}.art-bars i:nth-child(6){height:100%}
        .section{padding:112px 0}.section.soft{background:var(--cloud)}.section-head{max-width:720px;margin:0 auto 55px;text-align:center}.section-label{display:inline-flex;align-items:center;gap:8px;margin-bottom:11px;color:var(--teal-dark);font-size:11px;font-weight:700}.section-label:before,.section-label:after{content:"";width:21px;height:1px;background:var(--teal);opacity:.55}.section-title{margin:0;color:var(--navy-900);font-size:clamp(29px,4vw,42px);line-height:1.55;letter-spacing:-1px;font-weight:900}.section-title span{color:var(--teal)}.section-sub{margin:13px 0 0;color:var(--muted);font-size:14px;line-height:2.1}.card-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.content-card{position:relative;padding:27px;background:#fff;border:1px solid #e1ebeb;border-radius:22px;transition:.28s;overflow:hidden}.content-card:hover{border-color:rgba(47,145,150,.4);transform:translateY(-7px);box-shadow:var(--shadow)}.card-icon{display:grid;width:55px;height:55px;margin-bottom:21px;place-items:center;color:var(--teal-dark);background:#e7f4f4;border-radius:17px}.card-icon svg{width:26px}.content-card h3{margin:0 0 9px;color:var(--navy);font-size:17px;font-weight:800}.content-card p{margin:0;color:var(--muted);font-size:12px;line-height:2}.feature-list{display:grid;gap:10px;margin-top:19px;padding:0;list-style:none}.feature-list li{display:flex;align-items:center;gap:8px;color:#53657a;font-size:11px}.feature-list li:before{content:"✓";display:grid;width:20px;height:20px;place-items:center;color:var(--teal-dark);background:#e6f4f3;border-radius:7px;font-size:10px;font-weight:900}.tag{display:inline-flex;margin-top:20px;padding:5px 10px;color:var(--teal-dark);background:#eaf6f6;border-radius:99px;font-size:9px;font-weight:700}
        .split{display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:80px}.split-copy .section-label:after{display:none}.split-copy .section-title{margin-bottom:19px}.split-copy>p{margin:0 0 25px;color:var(--muted);line-height:2.2}.check-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.check{display:flex;align-items:center;gap:9px;color:#465a70;font-size:11px;font-weight:600}.check i{display:grid;width:25px;height:25px;place-items:center;color:var(--teal-dark);background:#e5f3f2;border-radius:8px;font-style:normal}.visual-box{position:relative;min-height:430px;padding:34px;color:#fff;background:var(--navy-900);border-radius:30px;box-shadow:0 28px 65px rgba(15,48,91,.2);overflow:hidden}.visual-box:before{content:"";position:absolute;width:370px;height:370px;left:-150px;bottom:-210px;border:1px solid rgba(18,214,210,.22);border-radius:50%;box-shadow:0 0 0 58px rgba(18,214,210,.025),0 0 0 116px rgba(18,214,210,.018)}.visual-box>*{position:relative;z-index:2}
        .pricing-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;align-items:stretch}.price-card{position:relative;padding:31px;background:#fff;border:1px solid #e0eaea;border-radius:25px;transition:.28s}.price-card:hover{transform:translateY(-7px);box-shadow:var(--shadow)}.price-card.featured{color:#fff;background:var(--navy);border-color:var(--navy);box-shadow:0 26px 60px rgba(15,48,91,.2)}.popular{position:absolute;top:18px;left:18px;padding:5px 10px;color:var(--navy);background:var(--cyan);border-radius:99px;font-size:9px;font-weight:800}.price-name{color:var(--teal-dark);font-size:11px;font-weight:700}.featured .price-name{color:var(--cyan)}.price-card h3{margin:7px 0 6px;color:var(--navy);font-size:24px;font-weight:900}.featured h3{color:#fff}.price-card>p{min-height:52px;margin:0;color:var(--muted);font-size:11px}.featured>p{color:rgba(255,255,255,.6)}.price{margin:25px 0 22px;padding:17px 0;border-top:1px solid #e6eeee;border-bottom:1px solid #e6eeee;color:var(--navy);font-size:20px;font-weight:900}.featured .price{color:#fff;border-color:rgba(255,255,255,.12)}.price small{display:block;color:#8491a1;font-size:9px;font-weight:400}.featured .price small{color:rgba(255,255,255,.52)}.price-card .feature-list{min-height:178px}.featured .feature-list li{color:rgba(255,255,255,.72)}.featured .feature-list li:before{color:var(--cyan);background:rgba(18,214,210,.1)}.price-card .btn{width:100%;margin-top:24px}.featured .btn{color:var(--navy);background:#fff}.featured .btn:hover{background:var(--cyan)}
        .faq{max-width:850px;margin:auto}.faq details{margin-bottom:11px;padding:0 21px;background:#fff;border:1px solid #e1eaea;border-radius:16px}.faq summary{display:flex;min-height:65px;align-items:center;justify-content:space-between;gap:20px;color:var(--navy);font-weight:700;cursor:pointer;list-style:none}.faq summary::-webkit-details-marker{display:none}.faq summary:after{content:"+";display:grid;width:27px;height:27px;place-items:center;color:var(--teal-dark);background:#e7f4f4;border-radius:8px;font-size:17px}.faq details[open] summary:after{content:"−"}.faq details p{margin:0;padding:0 0 19px;color:var(--muted);font-size:12px;line-height:2}
        .values{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid rgba(255,255,255,.1);border-radius:24px;overflow:hidden}.value{padding:30px 24px;border-left:1px solid rgba(255,255,255,.1)}.value:last-child{border-left:0}.value b{display:block;margin:18px 0 8px;color:#fff;font-size:15px}.value p{margin:0;color:rgba(255,255,255,.56);font-size:11px}.value svg{width:27px;color:var(--cyan)}.dark-section{position:relative;padding:110px 0;color:#fff;background:var(--navy-900);overflow:hidden}.dark-section:before{content:"";position:absolute;inset:0;opacity:.11;background-image:radial-gradient(#fff .7px,transparent .7px);background-size:25px 25px}.dark-section .container{position:relative;z-index:2}.dark-section .section-title{color:#fff}.dark-section .section-label{color:var(--cyan)}
        .cta-wrap{padding:0 0 110px}.cta{position:relative;display:grid;grid-template-columns:1.25fr .75fr;align-items:center;min-height:270px;padding:50px 60px;overflow:hidden;color:#fff;background:linear-gradient(120deg,var(--teal-dark),var(--teal));border-radius:30px;box-shadow:0 27px 65px rgba(47,145,150,.22)}.cta:before{content:"";position:absolute;width:400px;height:400px;left:-150px;top:-230px;border:1px solid rgba(255,255,255,.23);border-radius:50%;box-shadow:0 0 0 60px rgba(255,255,255,.025),0 0 0 120px rgba(255,255,255,.018)}.cta-copy,.cta-action{position:relative;z-index:2}.cta h2{margin:0 0 10px;font-size:clamp(26px,4vw,38px);line-height:1.55;font-weight:900}.cta p{margin:0;color:rgba(255,255,255,.72);font-size:12px}.cta-action{display:flex;justify-content:flex-end}.cta .btn{color:var(--navy);background:#fff;box-shadow:0 15px 33px rgba(15,48,91,.17)}
        .site-footer{padding:60px 0 25px;color:rgba(255,255,255,.65);background:var(--navy-900)}.footer-grid{display:grid;grid-template-columns:1.6fr repeat(3,.8fr);gap:55px;padding-bottom:42px}.footer-brand img{width:70px;height:54px;object-fit:contain;filter:brightness(0) invert(1)}.footer-brand p{max-width:350px;margin:18px 0 0;font-size:11px;line-height:2.1}.footer-col h3{margin:0 0 17px;color:#fff;font-size:12px}.footer-col a{display:block;width:max-content;margin-bottom:9px;font-size:10px}.footer-col a:hover{color:var(--cyan)}.footer-bottom{display:flex;justify-content:space-between;padding-top:22px;border-top:1px solid rgba(255,255,255,.09);font-size:9px}.reveal{opacity:1;transform:none}.js .reveal{opacity:0;transform:translateY(22px);transition:opacity .65s,transform .65s}.js .reveal.visible{opacity:1;transform:none}
        /* Slightly larger type scale for improved Persian readability. */
        body{font-size:16px}.main-nav>a{font-size:15px}.portal-link{font-size:12px}.new-badge{font-size:10px}.breadcrumb,.section-label{font-size:13px}.page-hero p{font-size:18px}.art-chip{font-size:11px}.art-desc{font-size:13px}.section-sub{font-size:16px}.content-card p{font-size:14px}.feature-list li,.check{font-size:13px}.tag,.price-name,.popular{font-size:11px}.price-card>p{font-size:13px}.price small{font-size:11px}.faq details p{font-size:14px}.value p{font-size:13px}.cta p{font-size:14px}.footer-brand p{font-size:13px}.footer-col h3{font-size:14px}.footer-col a{font-size:12px}.footer-bottom{font-size:11px}
        .brand{width:auto;justify-content:flex-start;gap:9px;flex:0 0 auto}.brand-copy{display:flex;min-width:100px;flex-direction:column;align-items:center;justify-content:center;line-height:1.35;text-align:center;white-space:nowrap}.brand-copy strong{color:var(--navy);font-size:15px;font-weight:900}.brand-copy small{margin-top:2px;color:#6d8298;font-size:9px;font-weight:600}
        @media(max-width:1050px){.brand-copy{min-width:0}.brand-copy small{display:none}.main-nav{gap:18px}.portal-link{padding-inline:9px}.card-grid{grid-template-columns:repeat(2,1fr)}.values{grid-template-columns:repeat(2,1fr)}.value:nth-child(2){border-left:0}.value:nth-child(-n+2){border-bottom:1px solid rgba(255,255,255,.1)}}
        @media(max-width:840px){.site-header{height:74px}.menu-toggle{display:grid}.desktop-portals{display:none}.brand{width:62px;height:47px;flex-basis:62px}.brand img{width:60px;height:45px}.main-nav{position:fixed;inset:74px 16px auto;display:grid;gap:0;padding:15px;background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow);opacity:0;visibility:hidden;transform:translateY(-12px);transition:.25s}.main-nav.open{opacity:1;visibility:visible;transform:none}.main-nav>a{padding:11px 10px;border-bottom:1px solid #edf2f2}.main-nav>a:after{display:none}.mobile-portals{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding-top:14px}.mobile-portals .tracking{grid-column:1/-1}.mobile-portals .portal-link{min-height:46px}.page-hero{padding:130px 0 80px}.hero-inner{grid-template-columns:1fr;gap:45px}.hero-copy{text-align:center}.breadcrumb,.hero-actions{justify-content:center}.page-hero p{margin-inline:auto}.hero-art{width:min(520px,100%);margin:auto}.split{grid-template-columns:1fr;gap:45px}.visual-box{order:2}.pricing-grid{grid-template-columns:1fr;max-width:550px;margin:auto}.price-card .feature-list{min-height:auto}.cta{grid-template-columns:1fr;gap:28px;text-align:center}.cta-action{justify-content:center}.footer-grid{grid-template-columns:1.4fr 1fr 1fr}.footer-brand{grid-column:1/-1}}
        @media(max-width:840px){.brand{width:auto;gap:7px;flex-basis:auto}.brand-copy{min-width:92px}.brand-copy strong{font-size:14px}.brand-copy small{display:block;font-size:8px}}
        @media(max-width:580px){.container{width:calc(100% - 28px)}.page-hero h1{font-size:35px;letter-spacing:-1px}.page-hero p{font-size:13px}.hero-actions{display:grid}.hero-actions .btn{width:100%}.hero-art{min-height:315px}.art-panel{padding:20px}.section{padding:78px 0}.section-head{margin-bottom:38px}.section-title{font-size:28px}.card-grid,.check-grid{grid-template-columns:1fr}.content-card{padding:24px}.values{grid-template-columns:1fr}.value{border-left:0;border-bottom:1px solid rgba(255,255,255,.1)}.value:nth-child(3){border-bottom:1px solid rgba(255,255,255,.1)}.value:last-child{border-bottom:0}.dark-section{padding:78px 0}.cta-wrap{padding-bottom:78px}.cta{padding:38px 22px;border-radius:23px}.footer-grid{grid-template-columns:1fr 1fr;gap:32px 20px}.footer-brand{grid-column:1/-1}.footer-bottom{gap:10px;flex-direction:column}}
        @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*:before,*:after{animation-duration:.01ms!important;transition-duration:.01ms!important}}
        @stack('styles')
    </style>
</head>
<body>
<a class="skip" href="#main-content">رفتن به محتوای اصلی</a>
<header class="site-header">
    <div class="container nav-wrap">
        <a class="brand" href="{{ route('home') }}" aria-label="سپند، صفحه اصلی">
            <img src="{{ asset('assets/images/brand/sepand-provided-header.png') }}" alt="" aria-hidden="true">
            <span class="brand-copy" aria-hidden="true"><strong>سپند</strong><small>CRM هوشمند حمل‌ونقل</small></span>
        </a>
        <nav class="main-nav" id="main-nav" aria-label="منوی اصلی">
            <a href="{{ route('modules') }}" @class(['active' => request()->routeIs('modules', 'site.modules.show', 'site.transport-modes.show')])>ماژول‌ها</a>
            <a href="{{ route('pricing') }}" @class(['active' => request()->routeIs('pricing')])>تعرفه‌ها</a>
            <a href="{{ route('about') }}" @class(['active' => request()->routeIs('about')])>درباره ما</a>
            <a href="{{ route('home') }}#why-us">چرا سپند؟</a>
            <div class="portal-actions mobile-portals">
                <a class="portal-link tracking" href="{{ route('tracking') }}" data-ga-event="portal_click" data-ga-label="mobile_tracking"><span class="new-badge">جدید</span>رهگیری محموله</a>
                <a class="portal-link" href="{{ route('login') }}">پورتال مشتریان</a>
                <a class="portal-link primary" href="{{ route('organization.portal') }}" data-ga-event="portal_click" data-ga-label="mobile_organization_portal">پرتال سازمان</a>
            </div>
        </nav>
        <div class="portal-actions desktop-portals">
            <a class="portal-link tracking" href="{{ route('tracking') }}" data-ga-event="portal_click" data-ga-label="desktop_tracking"><span class="new-badge">جدید</span>رهگیری محموله</a>
            <a class="portal-link" href="{{ route('login') }}">پورتال مشتریان</a>
            <a class="portal-link primary" href="{{ route('organization.portal') }}" data-ga-event="portal_click" data-ga-label="desktop_organization_portal">پرتال سازمان</a>
        </div>
        <button class="menu-toggle" id="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav" aria-label="باز کردن منو"><svg viewBox="0 0 24 24" fill="none"><path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></button>
    </div>
</header>
<main id="main-content">@yield('content')</main>
<footer class="site-footer">
    <div class="container">
        <div class="footer-grid">
            <div class="footer-brand"><a href="{{ route('home') }}"><img src="{{ asset('assets/images/brand/sepand-provided-header.png') }}" alt="سپند"></a><p>نرم‌افزار یکپارچه سپند برای مدیریت CRM، فروش، عملیات حمل، اسناد و مالی شرکت‌های فورواردری و لجستیک.</p></div>
            <div class="footer-col"><h3>محصول</h3><a href="{{ route('modules') }}">ماژول‌های نرم‌افزار</a><a href="{{ route('pricing') }}">تعرفه‌ها</a><a href="{{ route('site.modules.show', ['module' => 'transport-operations']) }}">عملیات حمل</a></div>
            <div class="footer-col"><h3>سپند</h3><a href="{{ route('about') }}">درباره ما</a><a href="{{ route('home') }}#why-us">مزیت‌های قابل سنجش</a><a href="{{ route('home') }}#process">Workflow محصول</a></div>
            <div class="footer-col"><h3>شروع همکاری</h3><a href="{{ route('consultation.create') }}" data-ga-event="cta_click" data-ga-label="footer_consultation">درخواست دمو و مشاوره</a><a href="{{ route('login') }}">پورتال مشتریان</a><a href="{{ route('organization.portal') }}">پرتال سازمان</a></div>
        </div>
        <div class="footer-bottom"><span>© {{ date('Y') }} سپند؛ تمامی حقوق محفوظ است.</span><span>طراحی‌شده برای تجربه‌ای شفاف‌تر</span></div>
    </div>
</footer>
<script>
(()=>{const menu=document.getElementById('main-nav'),toggle=document.getElementById('menu-toggle');toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));const track=(eventName,eventLabel,url)=>{const payload={event_category:'marketing',event_label:eventLabel,link_url:url||window.location.href};if(typeof window.gtag==='function')window.gtag('event',eventName,payload);else{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:eventName,...payload})}};document.addEventListener('click',event=>{const link=event.target.closest('[data-ga-event]');if(link)track(link.dataset.gaEvent,link.dataset.gaLabel||link.textContent.trim(),link.href)});document.querySelectorAll('[data-ga-form]').forEach(form=>form.addEventListener('submit',()=>track(form.dataset.gaForm,'consultation_form_submit',form.action)));const items=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});items.forEach(item=>observer.observe(item))}else items.forEach(item=>item.classList.add('visible'))})();
</script>
@stack('scripts')
</body>
</html>
